version: "3.8"

volumes:
    mariadb:
    wordpress:

networks:
    inception:

services:
    nginx:
        build: ./requirements/nginx/.
        restart: always
    mariadb: 
        build: ./requirements/mariadb/.
        restart: always
    wordpress:
        build: ./requirements/wordpress/.
        restart: always
    
